name: graduation_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  video_player: ^2.7.0
  image_picker: ^1.0.0 
  camera: ^0.10.0       
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  tflite_flutter: ^0.11.0
  permission_handler: ^11.0.0
  google_generative_ai: ^0.3.0
  # Using flutter_speech instead of speech_to_text to avoid compatibility issues
  flutter_tts: ^3.6.3
  # Alternative solution: use one of these instead of speech_to_text
  # Option 1:
  flutter_speech: ^2.0.0
  speech_to_text: ^7.0.0
  # Option 2 (comment out if using Option 1):
  # speech_to_text_macos: ^1.0.0
  # Option 3 (comment out if using Options 1 or 2):
  # flutter_voice_processor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/models/best.tflite
    - assets/models/classes.txt
  fonts:
    - family: Enriqueta
      fonts:
        - asset: Fonts/Enriqueta-Regular.ttf
        - asset: Fonts/Enriqueta-Bold.ttf
        - asset: Fonts/Enriqueta-Medium.ttf
        - asset: Fonts/Enriqueta-SemiBold.ttf
